### Update request to update a record
PUT http://localhost:8080/records/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhbmFAZ21haWwuY29tIiwicm9sZSI6IkFOQUxZU1QiLCJpYXQiOjE3NzUzMTQyOTcsImV4cCI6MTc3NTM1MDI5N30.sEhOwE-Uls-MXKtBWs93e0j5KPFQWXxE1WsYSQqdOcJt_UTisRVfRGgCVnheuzRa


{
  "amount": 500,
  "type": "income",
  "category": "Salary",
  "date": "2026-04-01",
  "notes": "daily salary"
}
###